config/routes.rb
Rails.application.routes.draw do

  resources :cocktails, only: [ :index, :show, :new, :create ]  do
    resources :doses, only: [ :new, :create ]
    resources :reviews, only: [ :show, :new, :create ]
  end
  resources :doses, only: [ :destroy ]

  root 'cocktails#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews

  validates :name, uniqueness: true, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :title, presence: true
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true}, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
    redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail, only: [ :index, :new, :create ]

  def index
    @reviews = @cocktail.reviews
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(reviews_params)
    @review.cocktail = @cocktail
    if @review.save
    redirect_to @cocktail
    else
      render new
    end
  end

  private

  def reviews_params
    params.require(:review).permit(:title, :content, :rating)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<%= render 'shared/banner' %>

<div class="wrapper">
  <div class="container">
    <div class="row">
      <h3 class="title-home">"This is not ‘Nam. This is bowling. There are rules.”</h3>
      <% @cocktails.each do |cocktail|%>
        <div class="col-xs-4">

          <% if cocktail.photo.url %>

          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path cocktail.photo.url, height: 300, width: 400, crop: :fill %>')">
            <div class="card-name">
              <h2><%= cocktail.name %></h2>
            </div>
            <%= link_to "", (cocktail_path(cocktail)), class: "card-link"%>
              <div class="product">
                  <div class="product-star">
                    <i class="fa fa-star">
                    </i>
                  </div>
              </div>
          </div>

          <% else %>

          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('https://www.cinephilesdreamago.com/wp-content/uploads/2015/10/the-big-lebowski-freres-coen-modernists-1.jpg')">
            <div class="card-name">
              <h2><%= cocktail.name %></h2>
            </div>
            <%= link_to "", (cocktail_path(cocktail)), class: "card-link"%>
              <div class="product">
                  <div class="product-star">
                    <i class="fa fa-star">
                    </i>
                  </div>
              </div>
          </div>

          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<style type="text/css">

body {
  background-image: url('https://images1.ocweekly.com/imager/u/original/8116990/big_lebowski_13.jpg');
}
.footer {
  position: fixed;
  bottom: 0;
}

</style>

<div class="container", style="margin-top: 200px;">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3" style= "color: white;">
      <%= simple_form_for [@cocktail] do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, placeholder: "White russian", html: {style: "margin-right: 10px;"}, label: 'Your username please', error: 'Username is mandatory, please specify one'  %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: "btn btn-treehouse"%>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<style type="text/css">

.footer {
  position: static;
  bottom: 0;
}

</style>

<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <% if @cocktail.photo.url %>
      <div class="cocktail-card">
        <%= cl_image_tag @cocktail.photo, height: 400, width: 400, crop: :fill, alt: "Avatar", style: "width: 515px;"%>
        <div class="content-cocktail" style="width: 400px">
          <h2>
            <%= @cocktail.name %>
          </h2>
        </div>
      </div>
      <% else %>
        <div class="cocktail-card">
          <%= image_tag "http://www.tastecocktails.com/wp-content/uploads/2016/11/WhiteRussian720FB.jpg", height: 400, width: 515, crop: :fill, alt: "Avatar", style: "width: 515px;"%>
          <div class="content-cocktail" style="width: 400px">
            <h2>
              <%= @cocktail.name %>
            </h2>
          </div>
        </div>
        <% end %>
    </div>
    <div class="col-xs-3">
      <div class="row">
        <div class="col-xs-12">
          <div class="cocktail-card" id="ingredient" style="width: 500px;">
            <% @cocktail.doses.each do |dose|%>
              <p>
                <i class="fa fa-hand-o-right" aria-hidden="true"></i> <%= dose.ingredient.name %> <i class="fa fa-arrow-right" aria-hidden="true"></i> <%= dose.description %>
              <%= link_to dose_path(dose), method: :delete, data: {confirm: "Are you sure?"}, id: "delete", class: "btn btn-danger"  do %>
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              <% end %>
              </p>
              <div class="separate"></div>
            <% end %>

            <%= link_to "Add a ingredient", new_cocktail_dose_path(@cocktail), id: "add", class: "btn btn-treehouse" %>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <div class="cocktail-card" id="review" style="width: 500px;">
                <% sum = 0 %>
                <% @cocktail.reviews.each do |review|%>
                  <p><%= review.title %> - <%= review.content %> - <%= review.rating %>  <i class="fa fa-star" aria-hidden="true"></i></p>
                  <% sum += review.rating %>
                  <div class="separate"></div>
                <% end %>
                <% if @cocktail.reviews.count != 0 %>
                  <%= average = (sum / @cocktail.reviews.count) %>
                <% else %>
                <% end %>
                <%= link_to "Add a review", new_cocktail_review_path(@cocktail), id: "add", class: "btn btn-treehouse" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<style type="text/css">

body {
  background-image: url('https://images1.ocweekly.com/imager/u/original/8116990/big_lebowski_13.jpg');
}
.footer {
  position: fixed;
  bottom: 0;
}

</style>

<div class="container" style="margin: 140px;">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3" style= "margin-top: 60px; margin-bottom: 40px; color: white;">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :ingredient_id, collection: Ingredient.all %>
        <%= f.input :description %>
        <%= f.button :submit, class: "btn btn-treehouse", style: "margin-left: 200px;"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/reviews/new.html.erb
<style type="text/css">

body {
  background-image: url('https://images1.ocweekly.com/imager/u/original/8116990/big_lebowski_13.jpg');
}
.footer {
  position: fixed;
  bottom: 0;
}

</style>

<div class="container" style="margin: 140px;">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3" style= "margin-top: 60px; margin-bottom: 40px; color: white;">
      <%= simple_form_for [@cocktail, @review] do |f| %>
        <%= f.input :title %>
        <%= f.input :content %>
        <%= f.input :rating, collection: 0..5, selected: 3 %>
        <%= f.button :submit, class: "btn btn-treehouse", style: "margin-left: 200px;"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://cdn-image.travelandleisure.com/sites/default/files/1495660520/big-lebowski-still-LEBOWSKIFEST0517.jpg');">
  <div class="banner-content">
    <%=image_tag("sun.png")%>
    <h1>The Dude</h1>
    <p>F*ck it, Dude. Let’s go bowling.</p>
    <%= link_to "Add a White Russian", new_cocktail_path, class: "btn btn-treehouse" %>
    <%=  %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="http://uproxx.com/movies/20-big-lebowski-quotes/"><i class="fa fa-github"></i></a>
    <a href="http://uproxx.com/movies/20-big-lebowski-quotes/"><i class="fa fa-instagram"></i></a>
    <a href="http://uproxx.com/movies/20-big-lebowski-quotes/"><i class="fa fa-facebook"></i></a>
    <a href="http://uproxx.com/movies/20-big-lebowski-quotes/"><i class="fa fa-twitter"></i></a>
    <a href="http://uproxx.com/movies/20-big-lebowski-quotes/"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    “Obviously you’re not a golfer.” — The Dude
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/cocktails" class="navbar-wagon-brand">
    <img src="https://orig00.deviantart.net/963f/f/2013/261/7/b/7b20f56dd053fc5e37c6db83fff4c9c2-d4brew7.png" alt="logo" class="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Create my White Russian", new_cocktail_path, class: "btn btn-treehouse" %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>